apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flora-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: flora-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flora-frontend
                port:
                  number: 3000
