apiVersion: v1
kind: Service
metadata:
  name: flora-backend
spec:
  selector:
    app: flora-backend
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: flora-frontend
spec:
  selector:
    app: flora-frontend
  ports:
    - port: 3000
      targetPort: 3000
